[project]
name = "PROJECT_NAME"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "uvicorn>=0.52.1",
]

[dependency-groups]
dev = ["mypy>=1.20.0", "pytest>=9.0.2", "pytest-cov>=7.1.0", "ruff>=0.15.8"]

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "-v"
markers = [
    "unit: mark a test as a unit test",
    "integration: mark a test as an integration test",
]

[tool.ruff]
line-length = 120
target-version = "py314"
exclude = [
    ".git",
    ".venv",
    "__pycache__",
    ".pytest_cache",
    ".mypy_cache",
    "alembic",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "C",  # flake8-comprehensions
    "B",  # flake8-bugbear
    "UP", # pyupgrade
]
ignore = ["E501", "C901"]

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true

[tool.mypy]
python_version = "3.14"
mypy_path = "src"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
ignore_missing_imports = true

[tool.pyright]
extraPaths = ["src"]
