"""add csrf token to auth sessions

Revision ID: 639486243669
Revises: 0b8ce0e2b3ed
Create Date: 2026-08-19 04:28:09.281897

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '639486243669'
down_revision: Union[str, Sequence[str], None] = '0b8ce0e2b3ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_sessions', sa.Column('csrf_token_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_sessions', 'csrf_token_hash')
    # ### end Alembic commands ###
