"""add message owner

Revision ID: 91c6f022b77c
Revises: 639486243669
Create Date: 2026-08-19 05:34:50.002851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91c6f022b77c'
down_revision: Union[str, Sequence[str], None] = '639486243669'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('messages_user_id_fkey', 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_column('messages', 'user_id')
    # ### end Alembic commands ###
